
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  # note the name is the DB services/pods  not the Cluster name.
  name: usdf-panda-idds
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: idds
      owner: panda
      secret:
        name: usdf-panda-idds-dev-creds
      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS pg_cron;
        - GRANT USAGE ON SCHEMA cron TO rubin;

  imageName: lsstsqre/cloudnative-pg:14
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: 'true' 

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  postgresql:
    shared_preload_libraries: [ 'pg_cron', 'pg_partman_bgw' ]
    parameters:
      shared_buffers: 32GB
      max_connections: "1000"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      work_mem: 128MB

  resources:
    requests:
      memory: 128Gi
      cpu: 16
    limits:
      memory: 256Gi
      cpu: 32

  storage:
    storageClass: wekafs--sdf-k8s01
    size: 1000Gi


