
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: usdf-panda-idds
spec:
  backup:
    retentionPolicy: "7d"
    barmanObjectStore:
      destinationPath: s3://rubin-usdf-panda-idds
      endpointURL: https://s3dfrgw.slac.stanford.edu
      s3Credentials:
        accessKeyId:
          name: s3-creds-idds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-creds-idds
          key: ACCESS_SECRET_KEY
  instances: 2
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: idds
      owner: rubin
      secret:
        name: usdf-panda-idds-creds
  
  imageName: lsstsqre/cloudnative-pg:14
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: 'true'

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  postgresql:
    shared_preload_libraries: [ 'pg_cron', 'pg_partman_bgw' ]
    parameters:
      shared_buffers: 32GB
      max_connections: "1000"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      work_mem: 128MB
#      ldap:
#        scheme: ldaps
#        server: 'ldap-unix.slac.stanford.edu'
#        # tls: true
#        port: 636
#        bindAsAuth:
#          prefix: 'uid='
#          suffix: ',ou=Accounts,dc=slac,dc=stanford,dc=edu'


  resources:
    requests:
      memory: 128Gi
      cpu: 16
    limits:
      memory: 256Gi
      cpu: 32

  storage:
    storageClass: wekafs--sdf-k8s01
    size: 3000Gi


