
resources:
- ns.yaml
# cnpg
#- ../../base/cnpg
- cnpg-panda-idds-database.yaml
- cnpg-panda-idds-pooler.yaml
- backup.yaml

#patches:
#- endpoints-patch.yaml

secretGenerator:
- name: usdf-panda-idds-prod-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password
- name: s3-creds
  options:
    disableNameSuffixHash: true
  files:
  - ACCESS_KEY_ID=etc/.secrets/access-key
  - ACCESS_SECRET_KEY=etc/.secrets/secret-key

#nameSuffix: -dev
namespace: panda-db
commonLabels:
  env: prod
  app: panda-idds
  namespace: panda-db

