
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  # note the name is the DB services/pods  not the Cluster name.
  name: usdf-panda-server
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: panda_db
      owner: panda
      secret:
        name: usdf-panda-server-dev-creds
  
  imageName: lsstsqre/cloudnative-pg:14
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: 'true' 

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  postgresql:
    shared_preload_libraries: [ 'pg_cron', 'pg_partman_bgw' ]
    parameters:
      shared_buffers: 32GB
      max_connections: "1000"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      work_mem: 128MB
    pg_hba:
      - local all panda trust
      - host all panda localhost trust
      - local all postgres trust
      - host all postgres localhost trust
      - host all all 0.0.0.0/0 md5
      - host all all ::0/0 md5
      - host all postgres 0.0.0.0/0 reject
      - host all postgres ::0/0 reject

  resources:
    requests:
      memory: 128Gi
      cpu: 16
    limits:
      memory: 256Gi
      cpu: 32

  storage:
    storageClass: wekafs--sdf-k8s01
    size: 1000Gi


