apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  labels:
    app: panda-idds2
    env: prod
    namespace: panda-db
  name: usdf-panda-idds2-pooler-transaction-rw
  namespace: panda-db
spec:
  cluster:
    name: usdf-panda-idds2
  instances: 3
  pgbouncer:
    parameters:
      default_pool_size: "500"
      idle_transaction_timeout: "0"
      log_connections: "1"
      log_disconnections: "1"
      max_client_conn: "1000"
      server_idle_timeout: "0"
      tcp_keepalive: "1"
      tcp_keepcnt: "1"
      tcp_keepidle: "1"
      tcp_keepintvl: "1"
      tcp_user_timeout: "21600"
    paused: false
    poolMode: transaction
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: pooler-transaction
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pooler-transaction
            topologyKey: kubernetes.io/hostname
      containers:
      - name: pgbouncer
        resources:
          limits:
            cpu: "1.0"
            memory: 500Mi
          requests:
            cpu: "1.0"
            memory: 100Mi
  type: rw