apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: usdf-panda-idds2
  namespace: panda-db
spec:
  #backup:
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    enabled: true
    isWALArchiver: true
    parameters:
      barmanObjectName: s3-store-idds

  instances: 2
  primaryUpdateStrategy: unsupervised

  imageName: ghcr.io/lsst-sqre/cnpg-postgres-images:17.5
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: 'true'

  enablePDB: true
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  postgresql:
    shared_preload_libraries: [ 'pg_cron', 'pg_partman_bgw' ]
    parameters:
      shared_buffers: 32GB
      max_connections: "1000"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      work_mem: 128MB
      jit: "off"

  resources:
    requests:
      memory: 64Gi
      cpu: 8
    limits:
      memory: 64Gi
      cpu: 8

  storage:
    storageClass: wekafs--sdf-k8s01
    size: 3000Gi
