resources:
- ns.yaml
- database.yaml
- backup.yaml

secretGenerator:
- name: usdf-panda-idds-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password
- name: s3-creds-idds
  options:
    disableNameSuffixHash: true
  files:
  - ACCESS_KEY_ID=etc/.secrets/access-key
  - ACCESS_SECRET_KEY=etc/.secrets/secret-key

namespace: panda-db
commonLabels:
  env: prod
  app: panda-idds
  namespace: panda-db
