apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  # note the name is the DB services/pods  not the Cluster name.
  name: usdf-panda-server2
  namespace: panda-db
spec:
  #backup:
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    enabled: true
    isWALArchiver: true
    parameters:
      barmanObjectName: s3-store-server
  startDelay: 300
  instances: 2
  primaryUpdateStrategy: unsupervised

  imageName: ghcr.io/lsst-sqre/cnpg-postgres-images:17.5
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: 'true' 

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  postgresql:
    shared_preload_libraries: [ 'pg_cron', 'pg_partman_bgw' ]
    parameters:
      shared_buffers: 32GB
      max_connections: "1000"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      work_mem: 128MB
      jit: "off"
    pg_hba:
      - local all rubin trust
      - host all rubin localhost trust
      - local all postgres trust
      - host all postgres localhost trust
      - host all all 0.0.0.0/0 md5
      - host all all ::0/0 md5
      - host all postgres 0.0.0.0/0 reject
      - host all postgres ::0/0 reject

  resources:
    requests:
      memory: 64Gi
      cpu: 8
    limits:
      memory: 96Gi
      cpu: 12

  storage:
    storageClass: wekafs--sdf-k8s01
    size: 3000Gi
