
resources:
- ns.yaml
# cnpg
- database.yaml
- backup.yaml

secretGenerator:
- name: usdf-panda-server-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password
- name: s3-creds-server
  options:
    disableNameSuffixHash: true
  files:
  - ACCESS_KEY_ID=etc/.secrets/access-key
  - ACCESS_SECRET_KEY=etc/.secrets/secret-key

namespace: panda-db
